/* 
 * 路由表对象：
 * 该文件挂载在Vue原型中 $mRoutesConfig
 * 作用：调用$mRouter对象的方法 传入以下对应的路由对象，详细见common目录下的router.js
 * 示例：this.$mRouter.push({route:this.$mRoutesConfig.main,query:{a:1}})
 * 注意：所有在pages目录下新建的页面都必须在"路由表"中进行声明，并且在框架的pages.json注册。
 * 
 * 配置参数项说明： 
 * name:可选配置 （路由名称）
 * path:必填配置 （路由地址）
 * requiresAuth:可选配置 （是否权限路由）
 */
export default {
	index:{
		name:'首页',
		path:'/pages/index/index',
		requiresAuth:false
	},
	login:{
		name:'登录',
		path:'/pages/login/login',
		requiresAuth:false
	},
	bindTel:{
		name:'绑定手机号',
		path:'/pages/login/bindTel',
		requiresAuth:false
	},
	gzh_login:{
		name:'公众号登录',
		path:'/pages/login/gzh_login',
		requiresAuth:false
	},
	reg:{
		name:'注册',
		path:'/pages/login/reg',
		requiresAuth:false
	},
	user_agreement:{
		name:'用户注册协议',
		path:'/pages/login/user_agreement',
		requiresAuth:false
	},
	forget:{
		name:'忘记密码',
		path:'/pages/login/forget',
		requiresAuth:false
	},
	mine:{
		name:'我的',
		path:'/pages/mine/mine',
		requiresAuth:false
	},
	blank:{
		name:'空白',
		path:'/pages/mine/blank',
		requiresAuth:false
	},
	user_auth:{
		name:'用户认证',
		path:'/pages/mine/user_auth/user_auth',
		requiresAuth:false
	},
	company_auth:{
		name:'企业认证',
		path:'/pages/mine/user_auth/company_auth',
		requiresAuth:false
	},
	company_agree:{
		name:'企业认证通过',
		path:'/pages/mine/user_auth/company_agree',
		requiresAuth:false
	},
	person_auth:{
		name:'个人认证',
		path:'/pages/mine/user_auth/person_auth',
		requiresAuth:false
	},
	person_agree:{
		name:'个人认证通过',
		path:'/pages/mine/user_auth/person_agree',
		requiresAuth:false
	},
	audit:{
		name:'用户认证审核中',
		path:'/pages/mine/user_auth/audit',
		requiresAuth:false
	},
	audit_refuse:{
		name:'用户认证审核被拒',
		path:'/pages/mine/user_auth/audit_refuse',
		requiresAuth:false
	},
	vip:{
		name:'我的会员',
		path:'/pages/mine/vip/vip',
		requiresAuth:false
	},
	vip_aggrement:{
		name:'会员入驻协议',
		path:'/pages/mine/vip/vip_aggrement',
		requiresAuth:false
	},
	buy_vip:{
		name:'我的会员购买',
		path:'/pages/mine/vip/buy_vip',
		requiresAuth:false
	},
	myfriends:{
		name:'我的好友',
		path:'/pages/mine/friends/myfriends',
		requiresAuth:false
	},
	friends_detail:{
		name:'我的好友明细',
		path:'/pages/mine/friends/friends_detail',
		requiresAuth:false
	},
	agency_award:{
		name:'代理奖励',
		path:'/pages/mine/agency/agency_award',
		requiresAuth:false
	},
	apply_agency:{
		name:'申请代理',
		path:'/pages/mine/agency/apply_agency',
		requiresAuth:false
	},
	agency_refuse:{
		name:'申请代理拒绝',
		path:'/pages/mine/agency/agency_refuse',
		requiresAuth:false
	},
	wallet:{
		name:'我的钱包',
		path:'/pages/mine/wallet/wallet',
		requiresAuth:false
	},
	recharge:{
		name:'充值',
		path:'/pages/mine/wallet/recharge',
		requiresAuth:false
	},
	deposit:{
		name:'提现',
		path:'/pages/mine/wallet/deposit',
		requiresAuth:false
	},
	connect:{
		name:'联系记录',
		path:'/pages/mine/connect/connect',
		requiresAuth:false
	},
	code:{
		name:'推荐码',
		path:'/pages/mine/code/code',
		requiresAuth:false
	},
	message:{
		name:'系统消息',
		path:'/pages/mine/message/message',
		requiresAuth:false
	},
	insurance:{
		name:'购买保险',
		path:'/pages/mine/insurance/insurance',
		requiresAuth:false
	},
	set:{
		name:'设置',
		path:'/pages/mine/set/set',
		requiresAuth:false
	},
	set_info:{
		name:'个人资料',
		path:'/pages/mine/set/set_info',
		requiresAuth:false
	},
	checkphone1:{
		name:'修改手机号',
		path:'/pages/mine/set/checkphone1',
		requiresAuth:false
	},
	checkphone2:{
		name:'修改手机号2',
		path:'/pages/mine/set/checkphone2',
		requiresAuth:false
	},
	check_pay:{
		name:'修改支付密码',
		path:'/pages/mine/set/check_pay',
		requiresAuth:false
	},
	check_login:{
		name:'修改登录密码',
		path:'/pages/mine/set/check_login',
		requiresAuth:false
	},
	customer:{
		name:'客服中心',
		path:'/pages/mine/customer/customer',
		requiresAuth:false
	},
	question:{
		name:'常见问题',
		path:'/pages/mine/customer/question',
		requiresAuth:false
	},
	customer_detail:{
		name:'常见问题详情',
		path:'/pages/mine/customer/customer_detail',
		requiresAuth:false
	},
	suggest:{
		name:'意见建议',
		path:'/pages/mine/customer/suggest',
		requiresAuth:false
	},
	service:{
		name:'在线客服',
		path:'/pages/mine/customer/service',
		requiresAuth:false
	},
	about:{
		name:'关于我们',
		path:'/pages/mine/customer/about',
		requiresAuth:false
	},
	adDetail:{
		name:'广告详情',
		path:'/pages/index/adDetail',
		requiresAuth:false
	},
	infoService:{
		name:'信息服务协议',
		path:'/pages/index/infoService',
		requiresAuth:false
	},
	issueDetail:{
		name:'信息详情',
		path:'/pages/issue/issueDetail',
		requiresAuth:false
	},
	report:{
		name:'举报',
		path:'/pages/report/report',
		requiresAuth:false
	},
	addIssue:{
		name:'发布招工',
		path:'/pages/issue/addIssue',
		requiresAuth:false
	},
	issue:{
		name:'我的发布',
		path:'/pages/issue/issue',
		requiresAuth:false
	},
	companyInfo:{
		name:'企业详情',
		path:'/pages/company/companyInfo',
		requiresAuth:false
	},
	train:{
		name:'培训',
		path:'/pages/train/train',
		requiresAuth:false
	},
	apply_train:{
		name:'培训机构入驻',
		path:'/pages/train/apply_train',
		requiresAuth:false
	},
	train_agree:{
		name:'培训机构入驻通过',
		path:'/pages/train/train_agree',
		requiresAuth:false
	},
	train_audit:{
		name:'培训机构入驻申请中',
		path:'/pages/train/train_audit',
		requiresAuth:false
	},
	train_refuse:{
		name:'培训机构入驻拒绝',
		path:'/pages/train/train_refuse',
		requiresAuth:false
	},
	trainSchoolDetail:{
		name:'培训机构详情',
		path:'/pages/train/trainSchoolDetail',
		requiresAuth:false
	},
	classDetail:{
		name:'课程详情',
		path:'/pages/train/classDetail',
		requiresAuth:false
	},
	selectPosition:{
		name:'选择职位',
		path:'/pages/selectPosition/selectPosition',
		requiresAuth:false
	},
	courseRegister:{
		name:'报名支付',
		path:'/pages/train/courseRegister',
		requiresAuth:false
	}
}